name: Run Azure Login with OpenID Connect

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.environment }}
      
    steps:

    - id: echo
      name: Echo
      env:
        ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
        ARM_CLIENT_ID: ${{ vars.TERRAFORM_ARM_CLIENT_ID }}
      run: |
        echo $ARM_TENANT_ID
        echo $ARM_CLIENT_ID
        echo $ARM_SUBSCRIPTION_ID

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ vars.TERRAFORM_ARM_CLIENT_ID }}
        tenant-id: ${{ vars.ARM_TENANT_ID }}
        subscription-id: ${{ vars.ARM_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'
      run: |
        az account show
        az group list
        pwd